### ISSUE TITLE
Window coordinates are broken?

### ISSUE THREAD

**Issue by jarrett** [PistonDevelopers/piston#937]
After upgrading to the latest Piston dependencies, window coordinates seem to be broken, at least on OSX. [Here is a screen capture](https://www.dropbox.com/s/ewvhe8anbnzyevl/piston-coordinates-error.mp4?dl=1) of the [Hello World example](https://github.com/PistonDevelopers/piston-examples/blob/master/src/hello_world.rs) demonstrating the error. The same thing occurs for every application I've tested, including the Piston examples and my home-grown apps.

**Comment by bvssvni** [comment]
Seems to be broken on the Glutin window back-end.

**Comment by bvssvni** [comment]
You can switch to `let window: PistonWindow<(), Sdl2Window> = ...` to fix the problem temporarily.

This requires `extern crate sdl2_window;` and `use sdl2_window::Sdl2Window;`.

**Comment by jarrett** [comment]
Thanks! Good to know. Should I post this issue to the [glutin_window Github](https://github.com/PistonDevelopers/glutin_window)?

**Comment by bvssvni** [comment]
Not necessary. It is probably a small fix.

**Comment by bvssvni** [comment]
The "user_input" example seem to work?

**Comment by bvssvni** [comment]
There is an issue on Glutin about the origin moving on Retina displays https://github.com/tomaka/glutin/issues/503

**Comment by bvssvni** [comment]
I guess that there are two bugs involved here, 1) that moves the origin and 2) related to resizing.

The "user_input" example is used to test backends but does not use `PistonWindow`. It could be that the second bug is triggered by `PistonWindow`.

**Comment by bvssvni** [comment]
`GlutinWindow` does not emit resize events.

**Comment by bvssvni** [comment]
The second bug is caused by https://github.com/tomaka/glutin/issues/445

**Comment by bvssvni** [comment]
I've fixed the second bug https://github.com/PistonDevelopers/piston_window/pull/74.

**Comment by jarrett** [comment]
Thanks!

So just to confirm, `PistonWindow`'s default config is still broken pending the `GlutinWindow` fix, correct?

In the meantime, `cargo update` and switching to `Sdl2Window` per your instructions above worked for me.

**Comment by bvssvni** [comment]
For Retina displays it is pending on https://github.com/tomaka/glutin/issues/503.

**Comment by willbush** [comment]
This might be related to an issue I have been running into when going through [sudoku tutorial](https://github.com/PistonDevelopers/Piston-Tutorials/tree/master/sudoku). I have been trying to figure out why my y-axis is off the screen. I finally cloned the Piston-Tutorial repo and ran the sudoku tutorial and saw that it works fine. However, I eventually realized it worked because it was using an older version of the dependencies in the `Cargo.lock` file. When I delete the `Cargo.lock` file, clean, and re-build it gets the latest version where the y axis is offset. See images below.

```
[dependencies]
# working version
piston = "0.35.0"
piston2d-graphics = "0.23.0"
piston2d-opengl_graphics = "0.49.0"
pistoncore-glutin_window = "0.42.0"

# latest version where screen is off 
# piston = "0.36.0"
# piston2d-graphics = "0.26.0"
# piston2d-opengl_graphics = "0.52.0"
# pistoncore-glutin_window = "0.45.3"
```

[image of working version](https://user-images.githubusercontent.com/2023546/37888478-6179db7e-308d-11e8-98f1-90020af87cc6.png)
[image of broken version](https://user-images.githubusercontent.com/2023546/37888479-6187e930-308d-11e8-9177-f8904c5d9b38.png)
